export const PRODUCTS = [
  {
    id: 1,
    name: "New Balance 564 Vintage Brights",
    img: "images/5.jpg",
    quantity: 1,
    nominal: 650,
    price: 650,
  },
  {
    id: 2,
    name: "New Balance 564 Vintage Brights",
    img: "images/6.jpg",
    price: 800,
    nominal: 800,
    quantity: 1,
  },
  {
    id: 3,
    name: "New Balance 564 Vintage Brights",
    img: "images/11.jpg",
    price: 1000,
    nominal: 1000,
    quantity: 1,
  },
  {
    id: 4,
    name: "New Balance 574 Vintage Brights",
    img: "images/0.jpg",
    price: 1200,
    nominal: 1200,
    quantity: 1,
  },
  {
    id: 5,
    name: "New Balance Made in UK 920 Chinese New Year",
    img: "images/13.jpg",
    price: 1400,
    nominal: 1400,
    quantity: 1,
  },
  {
    id: 6,
    name: "New Balance 574 Vintage Brights",
    img: "images/10.jpg",
    nominal: 1200,
    price: 1200,
    quantity: 1,
  },
];
export const PRODUCTSBASKET = [
  {
    id: 1,
    name: "New Balance 373 Modern Classics",
    img: "images/11.jpg",
    price: 1500,
    quantity: 1,
    nominal: 1500,
  },
  {
    id: 2,
    name: "New Balance 373 Modern Classics",
    img: "images/12.jpg",
    price: 1500,
    quantity: 1,
    nominal: 1500,
  },
];
